version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/laterlater" # Use the service name as the host

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
